services:
  - type: web
    name: intimidator-md
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_NAME
        value: Intimidator MD
      - key: PREFIX
        value: .
      - key: SESSION_ID
        sync: false
